// Firebase configuration for the Parlo Admin dashboard.
//
// This dashboard targets the SAME Firebase project as the mobile app
// (`parlo-ec41a`), so it reuses the project's web app configuration. The
// primary (and tested) target is Flutter Web running in Chrome; macOS is
// provided as a secondary desktop target.
//
// File generated by hand to avoid requiring the FlutterFire CLI; the values
// mirror `polyglot/lib/firebase_options.dart`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform. '
          'Run the admin dashboard on the web (-d chrome).',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcjDXfhLbTizunl2IVFvOJoKc3_i5d0Ng',
    appId: '1:1079591616493:web:abc18956dfaa6092bb31e4',
    messagingSenderId: '1079591616493',
    projectId: 'parlo-ec41a',
    authDomain: 'parlo-ec41a.firebaseapp.com',
    storageBucket: 'parlo-ec41a.firebasestorage.app',
    measurementId: 'G-0KLG2XQ5Y8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZkV8j9DpGrL4FMSxh8G6FDpBkQCNNtHI',
    appId: '1:1079591616493:ios:a0ac4618b2e2c99bbb31e4',
    messagingSenderId: '1079591616493',
    projectId: 'parlo-ec41a',
    storageBucket: 'parlo-ec41a.firebasestorage.app',
    iosBundleId: 'com.awab.polyglotAdmin',
  );
}
